config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'velib_stations/index'
  get 'services/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citybike.rb
# frozen_string_literal: true

class Citybike < ApplicationRecord
  include HTTParty
  base_uri "api.citybik.es"

  def data
    self.class.get("/v2/networks")
  end

  def networks
    data.parsed_response
  end
end

app/models/station.rb
# frozen_string_literal: true

class Station < ApplicationRecord
  include HTTParty
  base_uri "api.citybik.es"

  def data_velib
    self.class.get("/v2/networks/velib")
  end

  def stations
    data_velib.parsed_response
  end

  def self.freshness
    date = all.max_by(&:update_date).update_date
    date.strftime("%d/%m/%Y - %Hh%Mm%Ss")
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @stations = Station.all
    @closest_stations, @distances = ClosestStations.new([48.8721312, 2.3466598], 5).closest_stations
  end
end

app/controllers/services_controller.rb
# frozen_string_literal: true

class ServicesController < ApplicationController
  def index
    @networks = Citybike.new.networks
    # render json: @networks
  end
end

app/controllers/velib_stations_controller.rb
# frozen_string_literal: true

class VelibStationsController < ApplicationController
  def index
    @stations = Station.new.stations
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/services_helper.rb
# frozen_string_literal: true

module ServicesHelper
end

app/helpers/velib_stations_helper.rb
# frozen_string_literal: true

module VelibStationsHelper
end

app/views/home/_index_velib.html.erb
<div class="table-responsive">
  <table id="myTable" data-toggle="table" class="table table-striped table-hover" style="width:100%">
    <tr>
      <th data-sortable="true">latitude</th>
      <th data-sortable="true">longitude</th>
      <th data-sortable="true">name</th>
      <th data-sortable="true">status</th>
      <th data-sortable="true">slots</th>
      <th data-sortable="true">free bikes</th>
      <th data-sortable="true">distance</th>
    </tr>
    <% @closest_stations.each do |station| %>
    <tr>
      <td><%= station.latitude %></td>
      <td><%= station.longitude %></td>
      <td><%= station.name %></td>
      <td><%= station.status %></td>
      <td><%= station.slots %></td>
      <td><%= station.free_bikes %></td>
      <td><%= @distances[station.station_id].to_i %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/home/index.html.erb
<h1>Bienvenue sur l'app gobike en version beta beta</h1>
<div class="badge badge-secondary">
  Fraicheur des données : <%= @stations.freshness %>
</div>

<div class="">
  <%= link_to 'Services de vélo partagés en France', services_index_path, class: "badge badge-primary" %>
</div>

<div class="">
  <%= link_to 'Stations vélib', velib_stations_index_path, class: "badge badge-primary" %>
</div>

<div class="column">
  5 stations les plus proches de :
  <input type="text" name="latitude" value="48.8721312">
  <input type="text" name="longitude" value="2.3466598">
  <button class="btn btn-primary" type="button" name="button">Rafraichir</button>
</div>

<div class="">
  <%= render "index_velib" %>
</div>

<div id="mapid"></div>

<!-- Leaflet's JS -->
<script type="text/javascript">
  var map;

  function initmap() {
    // set up the map
    map = new L.Map('mapid').setView([48.8721312, 2.3466598], 16);

    // create the tile layer with correct attribution
    var osmUrl='http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
    var osmAttrib='Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> contributors';
    var osm = new L.TileLayer(osmUrl, {attribution: osmAttrib});

    // start the map in South-East England
    // map.setZoom(1).setView([30, 0]);
    map.addLayer(osm);
  }
  initmap();

  // extend class icons
  var LeafIcon = L.Icon.extend({
  	options: {
  		shadowUrl: '<%= image_url("marker_green.png") %>',
  		iconSize:     [5, 10]
  	}
  });

  var greenIcon = L.icon({
    iconUrl: '<%= image_url("marker_green.png") %>',
    iconSize: [30, 45],
    iconAnchor: [15, 45],
    popupAnchor: [0, -45],
  });

  var homeIcon = L.icon({
    iconUrl: '<%= image_url("icon_home.png") %>',
    iconSize: [45, 60],
    iconAnchor: [22.5, 60],
    popupAnchor: [0, -60],
  });

  // L.icon = function (options) {
  // 	return new L.Icon(options);
  // };

  // var greenIcon = new LeafIcon({iconUrl: 'marker_green.png'}),
  //     redIcon = new LeafIcon({iconUrl: 'marker_red.png'}),
  //     blackIcon = new LeafIcon({iconUrl: 'marker_black.png'});
  //     homeIcon =  new LeafIcon({iconUrl: 'icon_home.png'});

  // Stations marker
  <% @closest_stations.each do |station| %>
    var markerstation = L.marker([<%= station.latitude.to_f %>, <%= station.longitude.to_f %>], {
                                 icon: greenIcon
    }).addTo(map).bindPopup("<p><strong>Nom : <%= station.name %></strong></p><p>Vélos libres : <%= station.free_bikes %></p>");
  <% end %>

  // User position marker
  var markerstation = L.marker([48.8721312, 2.3466598], {
                               icon: homeIcon
  }).addTo(map).bindPopup("Je pars d'ici !");
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gobike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CDN CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
          
    <!-- Bootstrap table CSS -->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.css">

    <!-- Leaflet's CSS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>

    <!-- Leaflet's JS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <!-- Bootstrap table JS -->
    <script src="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.js"></script>

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/services/_index_FR.html.erb
<input type="text" id="myInput" onkeyup="searchBarTables()" placeholder="Rechercher un produit par ville..." title="Rentrer un nom">
<div class="table-responsive">
  <table id="myTable" data-toggle="table" class="table table-striped table-hover" style="width:100%">
    <tr>
      <th data-sortable="true">Id</th>
      <th data-sortable="true">Name</th>
      <th data-sortable="true">City</th>
      <th data-sortable="true">Compagny</th>
      <th data-sortable="true">Href</th>
    </tr>
    <% @networks["networks"].select { |e| e["location"]["country"] == "FR" }.each do |company| %>
    <tr>
      <td><%= company["id"] %></td>
      <td><%= company["name"] %></td>
      <td><%= company["location"]["city"] %></td>
      <td><%= company["company"] %></td>
      <td><%= company["href"] %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/services/index.html.erb
<h1>Services de vélos partagés en France</h1>
<p></p>

<%= render "index_FR" %>

app/views/velib_stations/_index_velib.html.erb
<div class="table-responsive">
  <table id="myTable" data-toggle="table" class="table table-striped table-hover" style="width:100%">
    <tr>
      <th data-sortable="true">latitude</th>
      <th data-sortable="true">longitude</th>
      <th data-sortable="true">name</th>
      <th data-sortable="true">status</th>
      <th data-sortable="true">slots</th>
      <th data-sortable="true">free bikes</th>
    </tr>
    <% @stations["network"]["stations"].each do |station| %>
    <tr>
      <td><%= station["latitude"] %></td>
      <td><%= station["longitude"] %></td>
      <td><%= station["name"] %></td>
      <td><%= station["extra"]["status"] %></td>
      <td><%= station["extra"]["slots"] %></td>
      <td><%= station["free_bikes"] %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/velib_stations/index.html.erb
<h1>Stations vélib</h1>
<p></p>

<%= render "index_velib" %>